# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ropehapi"

[social.params]
icon = "brand-github"

[[social]]
identifier = "coding-youtube"
name = "Coding Youtube channel"
url = "https://youtube.com/@ropehapiCoding"

[social.params]
icon = "brand-youtube"

[[social]]
identifier = "gaming-youtube"
name = "Gaming Youtube channel"
url = "https://youtube.com/@ropehapi"

[social.params]
icon = "brand-youtube"

[[social]]
identifier = "twitch"
name = "Twitch"
url = "https://twitch.tv/ropehapi"

[social.params]
icon = "brand-twitch"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/ropehapi"

[social.params]
icon = "brand-twitter"